---
title: "표본크기"
date: "2023-08-29"
output:
  pdf_document:
    latex_engine: xelatex
  word_document: default
mainfont: NanumGothic
---
# 파일 불러오기 

```{r message=FALSE}
setwd('C:\\Users\\phl02\\Desktop\\P\\bio_sas')
size<- read.csv("data\\ncm.csv")
size
```


\newpage  

# 분석 진행

```{r message=FALSE}
library(meta)
meta_size <- metabin(event.e,n1,event.c,n2,data=size,studlab = study,
                   sm='RR',method='Inverse')
meta_size
```  


\newpage  

# 그래프 
```{r, fig.width=11.5,warning=FALSE}
forest(meta_size,
       col.diamond = 'deepskyblue1',col.square = 'deeppink1')
```
\newpage  

# 누적
```{r,fig.width=11, message=FALSE}
meta_size2 <-metacum(meta_size,sortvar=study)
meta_size2
```

\newpage

# 그래프 
```{r, fig.width=11.5,warning=FALSE}
forest(meta_size2,
       col.diamond = 'deepskyblue1',col.square = 'deeppink1')
```

\newpage 

# 결과 정리 
```{r message=FALSE,warning=FALSE}
library(kableExtra)
library(stringr)
result <- matrix(0,7,6)
colnames(result) <- c('k','RR','95% CI_low',
                      '95% CI_up','I^2(%)','P')
result[,1] <- as.matrix(unique(unlist(str_extract_all(meta_size2$studlab,"[0-9]{1,}"))))
result[,2] <- c(0.67,0.67,0.69,0.73,0.74,0.91,0.92)
result[,3] <- c(0.47,0.53,0.57,0.63,0.64,0.86,0.87)
result[,4] <- c(0.94,0.85,0.85,0.85,0.86,0.96,0.97)
result[,5] <- round(na.omit(meta_size2$I2)*100,2)
result[,6] <- round(na.omit(meta_size2$pval),3)[1:7]

for(i in 1:nrow(result)){
  if (result[i,6] < 0.001) result[i,6]='<.001'
}

kable(result)

```


